.codeclimate.yml
README.md

enable duplication engine

---

src/index.js
test/hsetnx.js

also fixing duplicate code issue reported by codeclimate

test coverage on hsetnx should be 100%

---

README.md
src/index.js
test/hgetall.js
test/hmset.js
test/hsetnx.js
test/hvals.js
test/multi.js
test/sadd.js
test/sismember.js
test/smembers.js
test/srem.js

Test coverage

---

compat.md
package.json

1. merge to master
2. publish new release on github for the v1.7.0 tag.
3. run npm publish on master.

Release 1.7.0

---

compat.md
scripts/update-compat.js

Blacklist features that are:
* deprecated
* renamed
* not meant to be used by client
* internal

Cleanup compat table

---

package.json

Set npm config git-version-tag to false

Update version script

---

package.json
src/commands/sadd.js
src/commands/scard.js
src/commands/sismember.js
src/commands/smembers.js
src/commands/spop.js
src/commands/srem.js
test/commands/sadd.js
test/commands/scard.js
test/commands/sismember.js
test/commands/smembers.js
test/commands/spop.js
test/commands/srem.js

use Set for redis set-commands

---

CHANGELOG.md
src/commands/hset.js
src/commands/index.js
src/commands/type.js
test/commands/hset.js
test/commands/type.js

made sure to add a placeholder of zset so we don't forget to update TYPE later on when we add support for ZSET operations

add TYPE command

---

appveyor.yml

https://www.appveyor.com/updates/2016/11/01/

Yarn is now preinstalled on AppVeyor

---

.travis.yml
appveyor.yml
circle.yml
yarn.sh

Streamline travis build while at it, no need to install yarn manually anymore

update yarn.lock file on greenkeeper branches

---

CHANGELOG.md
src/index.js
test/exec.js

exec should support a callback argument

---

src/commands/set.js
test/commands/set.js

I basically just mimicked the logic in [fakeredis](https://github.com/guilleiguaran/fakeredis/blob/master/lib/redis/connection/memory.rb).

Update SET command with support for EX, PX, NX and XX

---

.npmignore
.vscode/settings.json
CHANGELOG.md
LICENSE
package.json
src/commands/smembers.js
src/commands/srem.js
test/commands/hvals.js
test/commands/lset.js
test/commands/publish.js
test/commands/rpoplpushBuffer.js
test/commands/rpush.js
test/commands/scard.js
test/commands/sdiff.js
test/commands/sinter.js
test/commands/smembers.js
test/commands/srem.js

* Hardened tests in other commands.
* Added LICENSE file to make the MIT license easier to spot on github.
* stricter npmignore to reduce package size.

Fix errors in smembers and srem when no data is set

---

src/command.js
src/commands/hgetall.js
src/commands/hmset.js
src/index.js
src/pipeline.js
test/command.js
test/commands/hmset.js

@stipsan  This PR is for argument and reply transformers (WIP)
#339 
Argument transformers are working. 
Interface is compatible, and conversion are from original lib. 
Need general feedback. And hints to insert reply transformers 
Why pipeline as single commands have different code ?

Transformers are coming

---

CHANGELOG.md
compat.md
package.json
yarn.lock

Release 3.5.0

---

src/command.js
test/command.js

Fix: Processing args can't handle  values (#352).

---

src/commands/del.js
test/commands/del.js

* Increment a counter if the key exists, and return that counter instead of the lenght of the arguments

Fixes #354

---

CHANGELOG.md
src/commands/srem.js
test/commands/keys.js
test/commands/srem.js

Fix inconsistent keys related to SREM

---

CHANGELOG.md

Chore: wrong changelog tag

---

src/commands/pexpire.js
src/expires.js
test/commands/pexpire.js
test/commands/pexpireat.js
test/commands/psetex.js

Fixes https://github.com/stipsan/ioredis-mock/issues/388

Fix pexpire to set correct expire time

---

.circleci/config.yml
renovate.json

It is a bit ridiculous to get daily PRs for this: https://github.com/stipsan/ioredis-mock/pull/400

lock to specific node version

---

src/commands/spop.js
test/commands/spop.js

I forgot a case in pr #432 : when `count === 1 && set.size === 1`
Sry for the double PR
😔😔😔

Fix missing case in spop

---

src/index.js
src/pipeline.js
test/multi.js

Add redis and _transactions properties on pipeline, to closer match ioredis.

Closer mock of pipeline/multi feature

---

src/commands/index.js
src/commands/zcount.js
test/commands/zcount.js

Added implementation for `zcount` in accordance with behaviour described in https://redis.io/commands/ZCOUNT

Feat: add zcount

---

CHANGELOG.md

Prepare 3.11.0

---

src/index.js

re #519 hopefully this is the only thing that is blocking ioredis v4 from working.

fix: ioredis v4 compatibility

---

compat.md
src/commands/index.js
src/commands/zremrangebyscore.js
test/commands/zremrangebyscore.js

Implementing https://redis.io/commands/zremrangebyscore.

feat: Implement ZREMRANGEBYSCORE

---

src/command.js

I was getting toString of undefined error. I probably did something wrong, but this should not crash.

fix: toString of undefined issue

---

src/commands/zremrangebyscore.js
test/commands/zremrangebyscore.js

This PR addresses https://github.com/stipsan/ioredis-mock/issues/604

fix: ZREMRANGEBYSCORE min/max args

---

src/commands/zadd.js
test/commands/zadd.js

This PR addresses https://github.com/stipsan/ioredis-mock/issues/605

feat: ZADD option support

---

README.md

I merged https://github.com/stipsan/ioredis-mock/pull/624 incorrectly so semantic-release isn't making a new release. This PR is solely to trigger that release.

fix: hdel shouldn't throw an error if key does not exist

---

package.json
yarn.lock

I'm annoyed by all these PRs: #642, #645, #649, #651

chore(devDependency): use npx for semantic-release

---

src/commands/defineCommand.js

bugfix:
1. line 47 of `defineCommand.js` condition is `if (result) ...` but it's not good, for example, if result be 0, it returns nil as a result.
2. base on Redis documentation, in Lua scripts all nil must convert to false, I fix that in `defineRedisObject` function. it makes bug if have a condition on `result == false` in Lua scripts.

fix: return value of redis.call method (lua scripts)

---

.github/workflows/nodejs.yml

if this works well than the other CIs are no longer needed :)

chore: test GH actions

---

src/commands/incrbyfloat.js
test/commands/incrbyfloat.js

fix: Initialize key on incrbyfloat command

---

compat.md
src/commands/index.js
src/commands/info.js
test/commands/info.js

feat: add info command

---

src/commands/zinterstore.js
test/commands/zinterstore.js

fix: zinterstore throws an error if key undefined

---

src/commands-utils/channel-subscription.js
src/commands-utils/emitMessage.js
test/commands/psubscribe.js
test/commands/publish.js
test/commands/punsubscribe.js

fix(publish): emit correct pmessage/messageBuffer/pmessageBuffer events

---

src/commands/xrange.js
test/commands/xrange.js

Reverts stipsan/ioredis-mock#1094
Tests are failing on macOS

revert: fix(xrange): handle full ids

---

compat.md
src/commands-utils/sha1.js
src/commands/eval.js
src/commands/evalsha.js
src/commands/index.js
src/index.js
test/commands/evalsha.js

this fixes https://github.com/stipsan/ioredis-mock/issues/1097

feat: #1097 evalsha support

---

.eslintignore
.eslintrc
.github/workflows/ci.yml
README.md
babel.config.js
jest.config.jestlegacy.js
jest.js
package-lock.json
package.json
src/commands/zpopmax.js
src/commands/zpopmin.js
src/commands/zrange.js
src/commands/zrangebyscore.js
src/commands/zrevrangebyscore.js
src/index.js
test/integration/keyspace-notifications.js
testSetupJestLegacy.js

feat: v7 breaking changes

---

src/commands-utils/emitMessage.js
test/integration/commands/publish.js

fixes https://github.com/stipsan/ioredis-mock/issues/1205

fix(publish): channel is Buffer for `messageBuffer` event

---

compat.md

A robot ran `node scripts/update-compat` and made this PR.

docs(compat.md): 🤖 ✨

---

scripts/update-compat.js

chore(prettier): 🤖 ✨

---

src/commands/xread.js
test/integration/commands/xread.js

A set of bugfixes for the XREAD command. Consult the individual commits for details.

fix: xread fixes

---

src/commands/rpoplpush.js
test/integration/commands/rpoplpush.js

Fixes https://github.com/stipsan/ioredis-mock/issues/1320
Inspired by `lmove` implementation

fix: rpoplpush should rotate the list when source and destintation are the same
