- .travis.yml
- appveyor.yml
The AppVeyor takes long enough to run builds already, the fact that windows builds run in sequence means this PR speeds them up by a 3x rate.
Travis runs them in parallel and does not suffer so much on the performance, but runs linting and submits codecoverage after every build. Meaning linting is done 3 times, and codecoverage is subtmitted 3 times with no difference between them.
> we only need to test the LTS release of Node

- package.json
Babel transpiled the src folder incorrectly, breaking the package on npm
> Fix broken package

- src/commands/del.js
See "JavaScript Leaks" section for reference:
https://webkit.org/blog/6425/memory-debugging-with-web-inspector/
> performance penalties for using delete

- package.json
Create a new github release right before publishing to npm.
This is in order for greenkeeper to include the github release in its PR's.
> update npm publish script

- src/index.js
Hey,
I know this is no a full-implementation of an event based mechanism, but it allows us to use ioredis-mock as we use ioredis.
Meaning:
```javascript
function createClient (options, isPrimary) {
const client = redis.createClient(options.port, options.hostname)
client.on('error', function (err) {
console.error(`An error occurred in ${redisClientName} redis`, err)
errorHandler(err)
})
client.on('connect', function () {
console.info(`Connection to ${redisClientName} redis established`)
connectHandler()
})
client.on('reconnecting', function () {
// Reconnection is managed directly by node redis
console.info(`Reconnecting to ${redisClientName} redis`)
reconnectingHandler()
})
client.on('end', function () {
console.warn(`Disconnected from ${redisClientName} redis`)
endHandler()
})
return …
```
> Add event emitter inheritance in order to use ioredismock as we use ioredis

- src/index.js
- test/events.js
This PR simply makes the redis mock trigger `connect` and `ready` events after instantiation (upon the next tick).
Would be nice to have this merged and published along with the previous commit which introduced the EventEmitter inheritance in the first place, as this is preventing us from using it, currently.
> Trigger connect & ready events on instantiation

- src/buffer.js
- src/commands/hdel.js
- src/commands/hincrby.js
- src/commands/hincrbyfloat.js
- src/commands/hmset.js
- src/commands/hset.js
- src/commands/hsetnx.js
- src/commands/lpop.js
- src/commands/lset.js
- src/commands/rpop.js
- src/commands/rpoplpush.js
- src/commands/sadd.js
- src/commands/smove.js
- src/commands/srem.js
- src/data.js
- test/buffer.js
- test/commands/getBuffer.js
- test/commands/hgetall.js
- test/data.js
I ran into an issue today when testing hash commands with ioredis-mock.
I had code similar to the below snippet where I was fetching a hash from Redis with `hgetall`,
sorting the value stored at one of the hash keys, and updating that value with `hset`.
When updating the Redis cache, the object returned from the call `hgetall` call was directly modified with the new values passed to `hset` because it was directly referencing the object stored in ioredis-mock's internal datastore:
```javascript
redis.multi([
['hgetall', myKey],
// ...
]).exec().then((cacheResult) => {
cacheResult.data = JSON.parse(cacheResult.data);
console.log(typeof cacheResult.data); // 'object'
/* modify cacheResult.data */
return redis.multi([
['hset', myKey, 'data', JSON.stringify(cacheResult.data)],
// ... …
```
> Don't modify objects passed to or returned from the internal datastore

- src/commands/hget.js
- src/commands/hgetall.js
- src/commands/hmget.js
- test/commands/hget.js
- test/commands/hgetall.js
- test/commands/hmget.js
This PR modifies the behavior of the `HGET` / `HMGET` / `HGETALL` commands to mimic that of ioredis:
- `HGET` now returns `null` if the hash doesn't exist or if the key doesn't exist in the hash
- `HMGET` now returns an array of `null`s if the hash doesn't exist
- `HGETALL` now returns an empty object (`{}`) if the hash doesn't exist
> fix hash get commands for missing hashes

- .codeclimate.yml
CodeClimate ESlint checks disabled as their version is consistently
behind ours.
> Only run ESlint checks on TravisCI for Pull Requests

- src/commands/index.js
- src/commands/lrange.js
- test/commands/lrange.js
This is very useful function, that has to be in a list.
- include tests
Spec: https://redis.io/commands/lrange
usage:
```js
/**
* @param {string} key
* @param {string} start Start index
* @param {string} end End index (included in returned range)
* @return {Array} An array in the defined range
*/
redis
.lrange('myKey', 0, 2)
.then(result => console.log(result))
```
> Add LRANGE support

- src/commands/index.js
- src/commands/subscribe.js
- test/commands/subscribe.js
Add `redis.subscribe('channel')` stub command, since there is a `publish` stub command.
> Add Subscribe Stub

- src/commands/srandmember.js
- test/commands/srandmember.js
Fixes:
- Combining `sadd` and `srandmember`.
- Fix positive count is bigger than the set is not randomized.
> Use `Set` for `srandmember`.

- src/commands/spop.js
- test/commands/spop.js
Fix #431. Make `spop` returning single value when count === 1. I took the opportunity to fully use [lodash](https://lodash.com) here.
> 🐛 #431 Fix spop behaviour 

- compat.md
- src/commands/index.js
- src/commands/zrange-command.common.js
- src/commands/zrevrangebyscore.js
- test/commands/zrevrangebyscore.js
* Add support for zrevrangebyscore
* Support optional parameter WITHSCORES for zrangebyscore and zrevrangebyscore
> Add zrevrangebyscore command

- src/commands/xread.js
- test/commands/xread.js
In my original pull request I used a wrong format how Redis returns on `xread` calls. This fix updates `ioredis-mock` to use the same format as described [here](https://redis.io/commands/xread).
> fix: redis format for xread for multiple streams.

- src/index.js
- test/multi.js
Just trying to support this basic interface of ioredis's
```
redis.pipeline([
['set', 'foo', 'bar'],
['get', 'foo']
]).exec(function () { /* ... */ });
```
> feat: add support for array of commands to pipeline()

- src/commands/zremrangebyrank.js
- src/commands/zremrangebyscore.js
- test/commands/zremrangebyrank.js
- test/commands/zremrangebyscore.js
Follow-up to #539 that mimics actual Redis behavior and avoids writing `undefined` back, which can lead to issues with `zadd`.
> fix: Don't write undefined with zrem*

- src/commands/zrange.js
- src/commands/zrangebyscore.js
- src/commands/zrevrangebyscore.js
- test/commands/zrange.js
Also enable case-insensitive use of WITHSCORES.
> fix: Support WITHSCORES in zrange

- compat.md
- src/commands/index.js
- src/commands/zscore.js
- test/commands/zscore.js
https://redis.io/commands/ZSCORE
> Returns the score of member in the sorted set at key.
> 
> If member does not exist in the sorted set, or key does not exist, nil is returned.
> 
> Return value
> Bulk string reply: the score of member (a double precision floating point number), represented as  string.
> feat: add zscore command

- package.json
- src/commands/brpoplpushBuffer.js
- src/commands/getBuffer.js
- src/commands/lpopBuffer.js
- src/commands/rpopBuffer.js
- src/commands/rpoplpushBuffer.js
Fixes #587 
The “buffer” aliases were causing the commands to get processed twice,
which resulted in the result being wrapped in an extra promise.
> fix: Buffer Command Aliases

- src/data.js
- src/expires.js
- src/index.js
- test/data.js
- test/keyprefix.js
Fixes #612
This PR is  support keyPrefix option  add keyPrefix test
```js
const cache = new MockRedis({keyPrefix: 'cache:'});
const car = new new MockRedis({keyPrefix: 'car:'});
async test() {
await cache.set('title', 'ioredis');
await car.set('title', 'nice car');
const cacheTitle = await cache.get('title');
const carTitle = await car.get('title');
console.log(cacheTitle === carTitle) // fasle
}
```
```js
it('should return  keys', done => {
// Given
const redis = new MockRedis({
data: {
foo: new Set(['foo0', 'foo1', 'foo2']),
zu: new Set(['ZU0', 'ZU1']),
},
keyPrefix: 'test:',
});
const stream = redis.scanStream();
// When
stream.pipe(writable);
writable.on('finish', () => {
// Then
expect(writable.flatData).toEqual(['test:foo', 'test:zu']);
done();
});
});
```
> feat: Support keyprefix option

- src/commands/hdel.js
- test/commands/hdel.js
if key does not exist return 0
as document states (https://redis.io/commands/hdel)
else an exception is thrown of "TypeError: Cannot convert undefined or null to object"
> fix: hdel shouldn't throw an error if key does not exist

- src/commands/del.js
- src/commands/expire.js
- src/commands/rename.js
- src/index.js
- src/keyspace-notifications.js
- test/commands/expire.js
- test/commands/rename.js
- test/keyspace-notifications.js
implemented: 
K     Keyspace events, published with __keyspace@<db>__ prefix.
E     Keyevent events, published with __keyevent@<db>__ prefix.
g     Generic commands (non-type specific) like DEL, EXPIRE, RENAME, ...
A     Alias for g$lshzxe, so that the "AKE" string means all the events.
NOT implemented - but could be added in future:
$     String commands
l     List commands
s     Set commands
h     Hash commands
z     Sorted set commands
x     Expired events (events generated every time a key expires)
e     Evicted events (events generated when a key is evicted for maxmemory)
> feat: add keyspace notification feature and add 'g' (generic) notifications

- src/commands-utils/readable-scan.js
- src/commands-utils/scan-command.common.js
- src/commands/hscan.js
- src/commands/sscan.js
- src/commands/zscan.js
- test/commands/hscan.js
- test/commands/scan.js
- test/commands/sscan.js
- test/commands/zscan.js
Hi, 
In `ioredis` all `*scan` commands returns nextCursor as string. In this PR I add same logic for ioredis-mock, because some 3prt utils have strict comparison to '0'.
Please, review it, and release new version if it posible. Thanks!
> fix: nextCursor in scan must be string

- compat.md
- src/commands/index.js
- src/commands/unlink.js
- test/commands/unlink.js
- Adds support for the `unlink` command.
- Delegates off to `del` as the behavior when running in memory would behave the same. I have verified that `unlink` sends the same keyspace notifications as `del` too. 
Fixes #746
> feat: add unlink command

- src/commands/defineCommand.js
- test/commands/eval.js
- test/lua.js
redis.pcall is the same as redis.call, but, if an internal error
of any kind happens, it returns 'a table', instead of failing.
It's unclear from the docs what this table is supposed to be.
The only place I've seen pcall used is in redlock, which ignores
the return value:
https://github.com/mike-marcacci/node-redlock/blob/e90e80a611c83a6a8c16912c7c5a8c6e9d49c617/redlock.js#L31
This is sufficient for redlock to "work" during our tests. Whether it's actually effective or not is a different matter. :)
> feat: implement lua redis.pcall

- src/commands/zrange-command.common.js
- src/commands/zrangebyscore.js
- src/commands/zrevrangebyscore.js
- test/commands/zrangebyscore.js
- test/commands/zrevrangebyscore.js
> fix: z(rev)?rangebyscore does not support negative limit count (#939)

- src/commands/decr.js
- src/commands/decrby.js
As reported in #877
Related docs:
* https://redis.io/commands/decr
* https://redis.io/commands/decrby
The setting of default key-value is already done in the `incr` and `incrby` commands. This PR brings that logic to the decrement commands.
Thanks
> Fixes #877: DECR and DECRBY defaults value if key doesn't exist

- .github/semantic.yml
This should stop blocking #987, #979, and #974
> chore: only validate PR titles

- src/commands/getset.js
- test/commands/getset.js
Return null for getset when is a new data set
More details on the issue: https://github.com/stipsan/ioredis-mock/issues/973
> fix: ioredis getset doesn't return null when saving new sets

- src/commands/ltrim.js
- test/commands/ltrim.js
in `ltrim`, negative start and end values were adjusted improperly adjusted when length + start still resulted in a negative value. Fixed to use slice offsets directly.
> fix: ltrim with negative start/end trims improperly

- src/commands/zscan.js
- test/commands/zscan.js
- test/commands/zscanStream.js
ZSCAN in *ioredis*:
```js
await redis.zadd('test', 1, 'a', 2, 'b', 3, 'c');
redis.zscan('test').then(console.log)
// logs: [ '0', [ 'a', '1', 'b', '2', 'c', '3' ] ]
```
ZSCAN in *ioredis-mock*:
```js
await redis.zadd('test', 1, 'a', 2, 'b', 3, 'c');
redis.zscan('test').then(console.log)
// logs: [ '0', [ 'a', 'b',  'c' ] ]
```
Fixed `zscan` and `zscanStream` implementation and related tests.
Related issue:
https://github.com/stipsan/ioredis-mock/issues/602
> fix: Make zscan and zscanStream match ioredis behaviour

- src/commands/hset.js
- test/commands/hset.js
As of Redis 4.0.0, HSET is variadic and allows for multiple field/value pairs.
This PR catches up with that.
> feat: HSET: add support for multiple fields

- src/commands/append.js
- test/commands/append.js
Added Buffer support to the append command.
It uses Buffer.concat which was added in node v0.7.11
> feat: add buffer support to append command

- src/commands/zrange-command.common.js
- test/commands/zrange.js
- test/commands/zremrangebyrank.js
This is a fix for this issue: https://github.com/stipsan/ioredis-mock/issues/992
> fix: negative stop offset larger than set size in zrange

- src/commands/quit.js
- src/index.js
- test/multiple-mocks.js
Repeatedly calling creating connected instances, subscribing to topics and then `.quit()`-ing leads to a memory leak, since listeners are never removed.
This PR fixes that.
> fix(Memory Leak): .quit() should remove subscriptions

- src/commands/index.js
- src/commands/linsert.js
- test/commands/linsert.js
> feat(commands): add new command LINSERT

- README.md
- src/index.js
- test/cluster.js
I'm using the following practice:
```js
const isUnittest = process.env.NODE_ENV === `unittest`
const Redis = require(isUnittest ? `ioredis-mock` : `ioredis`)
const cluster = new Redis.Cluster([`redis://xxxxx:6379`])
// more code here
```
But this lib does not seem to support cluster creation yet.
The `Redis.Cluster` constructor is all I need, hence I didn't dig deeply into the internal mechanisms of the redis cluster. I know this is far from complete, so feel free to give advice or simply reject for good :D
Related to #359
> feat: `Redis.Cluster` constructor support

- src/commands/defineCommand.js
- src/lua.js
- test/commands/defineCommand.js
Fix for issue #1042
Custom commands returning lists would unexpectedly return an extra `null` value at the beginning of the array. 
My initial fix broke a previous fix for one-based indices in lua so I rewrote it and added a test for that case as well.
> fix: Lua redis.call lists returning null

- src/commands/defineCommand.js
- test/commands/eval.js
Hi there! I observed a bug where `#arr` returns the wrong array length. This PR contains a reproduction test.
I haven't yet found a way to fix this easily - any ideas from the maintainers?
cc https://github.com/quirrel-dev/quirrel/issues/452
> test(lua): #arr is off-by-one because arrays are 1-based

- src/commands/xrange.js
- test/commands/xrange.js
Allow `xrange` to handle full ids returned from `xadd` (for example, `100-0`) as well as timestamp-only ids (for example, `100`).
> fix(xrange): handle full ids

- compat.md
- src/commands/index.js
- src/commands/smismember.js
- test/commands/smismember.js
This PR adds a mock implementation of `MISMEMBER`
[This Redis command was added in v6.2.0](https://redis.io/commands/smismember)
[And added to ioredis in v4.21.0](https://github.com/luin/ioredis/issues/1281)
[And I updated the typescript definitions here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56945)
> feat: Redis.SMISMEMBER support

- src/commands/xadd.js
- test/commands/xadd.js
While using this package, I noticed that it errors out then you pass an odd number of parameters to xadd, when it shouldnt, i.e
```
redis.xadd(
'stream',
'MAXLEN',
'~',
'50',
'*',
'reading',
'{"key": "value"}'
)
```
I believe the problem is unique to the "~" character, allowing for an odd number of params - reflected in this logic:
```
(args.includes('~') ? args.length < 4 : args.length % 2 !== 0)
```
I have also included an extra test that covers this.
May be applicable to other issues: https://github.com/stipsan/ioredis-mock/issues/1039
> fix(xadd): Accept odd number of parameters

- src/index.js
The io-redis types package supports the duplicate function, which is similar to what createConnectedClient does. I added the implementation of duplicate, which internally calls createConnectedClient.
> fix: Add duplicate function to support instance duplication for TypeScript mocks

- src/commands/type.js
current implementation of the type command misses the sorted set (zset) type while lots of other commands around sorted sets are implemented. This PR adds the missing code
> fix: add missing zset support for "type" command

- src/command.js
- src/index.js
- src/pipeline.js
- test/command.js
The transformers implementation was never compatible with ioredis, this fixes it by defining the transformer on the main export instead of the prototype and also adds much-needed tests.
Fixes: https://github.com/stipsan/ioredis-mock/issues/1051
> fix: Fix transformers

- jest.config.js
- src/commands/flushall.js
- src/commands/flushdb.js
- src/context.js
- src/data.js
- src/expires.js
- src/index.js
- test/command.js
- test/data.js
- test/expires.js
- test/keyprefix.js
- testSetupAfterEnv.js
- testSetupJest.js
I'm continuing the #997.
Closes #997 and #773
> feat(pubsub): Add shared context among Redis instances

- README.md
- test/commands/expire.js
- test/commands/psubscribe.js
- test/commands/publish.js
- test/commands/punsubscribe.js
- test/commands/rename.js
- test/commands/subscribe.js
- test/commands/unsubscribe.js
- test/keyspace-notifications.js
- test/multiple-mocks.js
The change in https://github.com/stipsan/ioredis-mock/pull/1110 should've been a major release, not a minor, to ensure we respect semver. This PR is the first step to rectify that mistake. Related to https://github.com/stipsan/ioredis-mock/issues/1113
Before v6, each instance of `ioredis-mock` lived in isolation:
```js
const Redis = require('ioredis-mock');
const redis1 = new Redis();
const redis2 = new Redis();
await redis1.set('foo', 'bar');
console.log(await redis1.get('foo'), await redis2.get('foo')); // 'bar', null
```
In v6 the [internals were rewritten](https://github.com/stipsan/ioredis-mock/pull/1110) to behave more like real life redis, if the host and port is the same, the context is now shared:
```js
const Redis = require('ioredis-mock');
const redis1 = new Redis();
const …
```
> feat: Share context between Redis instances

- README.md
- src/index.js
- test/integration/options-shorthand.js
Fixes #1120
Constructor shorthands now supported:
- `new Redis(6379, 'localhost', { keyPrefix: 'shared:' })`
- `new Redis('//localhost:6379', { keyPrefix: 'shared:' })`
- `new Redis('redis://localhost:6379', { keyPrefix: 'private:' })`
- `new Redis(6379, { keyPrefix: 'shared:' })`
- `new Redis(6379)`
- `new Redis('redis://localhost:6379/')`
> feat: add options shorthand

- src/commands/defineCommand.js
- test/integration/commands/defineCommand.js
This commit fixes a bug that causes HGETALL commands in Lua
to fail with ioredis-mock.
Redis returns an array reply for HGETALL. ioredis and ioredis-mock
convert this response to a JS object.
When using custom Lua scripts with ioredis, however, HGETALL returns
and array-like table. With this change, HGETALL will also return an
array-like table from Lua with ioredis-mock.
> fix: Return table for HGETALL from custom Lua scripts

- package.json
- src/command.js
Closes #1164
I don't have Linux so can't test in a case-sensitive environment 🤣.
Test plan:
1. Make sure tests pass with ioredis v4 and ioredis v5.
> feat: support ioredis v5

- src/index.js
- test/integration/cluster.js
This PR extends the experimental cluster support by passing along provided
Redis options in the cluster constructor.
Somewhat related to https://github.com/stipsan/ioredis-mock/issues/359
> feat: Redis Cluster pass redisOptions in constuctor

- src/pipeline.js
- test/integration/multi.js
As mentioned in the issue https://github.com/stipsan/ioredis-mock/issues/1046 accessing the queue length of the pipeline is different in the mocked version. Therefore I propose mapping `this.batch.length` to `this.length` in the pipeline
> fix: map batch length to length in pipeline

- src/index.js
This is required because some libraries will access the `.options` of Redis. E.g. https://github.com/swarthy/redis-semaphore/blob/master/src/utils/index.ts#L12
> fix: keep options as redis property

- src/commands/defineCommand.js
- test/integration/commands/eval.js
In lua 5.2, the global function unpack was moved to table.unpack.
closes #1193
> fix(lua): Expose unpack to imitate redis's lua 5.1 support

- src/index.js
- test/integration/commands/duplicate.js
fixes https://github.com/stipsan/ioredis-mock/issues/1207
> fix(duplicate): preserve options as well as accept overrides

- src/index.js
In the `ioredis` package there is a `Cluster.nodes('all' | 'slave' | 'master')`  method which is not supported here.
I implemented a short solution with an option to get master and slave nodes in the future.
> feat: implement nodes method in cluster mock

- src/index.js
- test/integration/cluster.js
Change variable name back from clusterNodes to nodes.
This will revert a breaking change, also tests won't fail.
> fix: change clusterNodes back to nodes

- src/commands/set.js
- test/integration/commands/set.js
Set allows for an optional parameter `"GET"`, which causes Redis to return the previous value of the key if it existed. This adds a conditional return value to the `set` command, which is `"OK"` if `"GET"` was not provided in the options and is key's previous value otherwise.
> fix(set): support optional "GET" parameter

- src/commands/zrange-command.common.js
- src/commands/zrange.js
- src/commands/zrangebyscore.js
- src/commands/zrevrange.js
- src/commands/zrevrangebyscore.js
- test/integration/commands/zrange.js
- test/integration/commands/zrangebyscore.js
- test/integration/commands/zrevrangebyscore.js
Starting with 6.2.0, Redis has deprecated `ZREVRANGE`, `Z[REV]RANGEBYSCORE` and `Z[REV]RANGEBYLEX` and added all of their params into `ZRANGE`.
This PR inherits Redis' new ZRange parsing function so that `ZRANGE` supports all the new parameters and so that all the "child" functions use the same algorithm.
In subsequent PRs I'm planning on adding support for `Z[REV]RANGEBYLEX` and, hopefully, `ZRANGESTORE`
> feat: refactor zrange

- src/index.js
- test/functional/commands.js
This allows monkey patching unsupported functions.
Closes #1258
> fix: Make unsupported commands writable

- src/commands-utils/scan-command.common.js
- src/commands/hscan.js
- test/integration/commands/hscan.js
- test/integration/commands/hscanStream.js
Fixes: https://github.com/stipsan/ioredis-mock/issues/962
Ref: https://redis.io/commands/scan/#return-value
> [HSCAN](https://redis.io/commands/hscan) [returns an] array of elements contain two elements, a field and a value, for every returned element of the Hash.
> fix: make `hscan` return flat list of entries

- src/pipeline.js
- test/integration/multi.js
Would you consider backporting https://github.com/stipsan/ioredis-mock/pull/1201 to v7.x?
I'm using the lib and I'm not ready to upgrade to v8 yet.
> fix: backport map batch length to length in pipeline.js

- src/commands/rpoplpush.js
- test/integration/commands/rpoplpush.js
Would you consider backporting https://github.com/stipsan/ioredis-mock/pull/1321 to v7.x?
I can't upgrade to v8 yet and I'm facing fix https://github.com/stipsan/ioredis-mock/issues/1320.
> fix: Backport rpoplpush should rotate the list when source and destintation are the same
